name: Test for pull request into the main branch
on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            # Keep up to date with the Node.js version of the project
            node-version: '22.14.0'
            
        - name: Install dependencies
          run: npm ci
        
        - name: Run tests
          run: npm run test
